language: python
python:
- '2.7'
install: pip install -r requirements.txt
script:
- mkdir _build
- doc2dash -fv --name 'Pythonista2' -d _build -i icon.png -j -I index.html Pythonista
- cp icon@2x.png _build/Pythonista2.docset
- cd _build && tar --exclude='.DS_Store' -cvzf Pythonista2.tgz Pythonista2.docset
deploy:
  provider: releases
  api_key:
    secure: KIS+dZJ1OPGkiJgNQmMjVDC3RKTUkT7Oc3oeR9BeDKf6tNVrV1akfbUWcaeru+uALnwzybyAzj3vm2PIeD5W2GoxwTesWvtL7dVeSMNDsKGC92Xe4GOM5FmdLEmCK9V9IiOaySd/2WcYOR8bTqMzt0aWNaVP3Ky5CGb7bFGkeKqfDg1LgwdkxxxzU9CPhIT7u7I3zRrNvsiDtlrjXSZyPta3kkL1w7ctlDX18SHjNlcuZlGg+THUQ1o56CX6n7NuNeexn57zRzdd/hU61iHqDRE48ekd9nwT3mZLXnhYwOk1IKRvsrjd+jGhqnuxi8mT/t9vtrF/oej03migCXXOdFaGC4pDffZ9AOIsolafAwmRlHIatCBvgdy1xzvwaAqrc1Phh1jzUPIbxxS86qxvsQHj+q3ZpvC9H5aV46RdYAqBfK/2nslRxg9bRhPUU3cknHkrt1YvoqJ3wTjJkFqgZJV9JLHueZffUPCobW22eF4IG4G3nnRzhlunEeeFnQdKKS+JtxzC0ifnv8u5EQBQx5JgxARfD7qqLSfuCzVUtg7d+EGFbIV5wasyTCGGsb8f1bopdGyWoNocHHLbeXZ0F18fK9v1Q1mAwEz8mJqGE/Ep/rdh8rWAt6Cx+7kBvwrMbJhqf3xXWZyrDTJNtEzYCCo3Le0MFF+nBe/xGtGOn2M=
  file:
  - _build/Pythonista2.docset
  - _build/Pythonista2.tgz
  skip_cleanup: true
  on:
    tags: true
